### ISSUE TITLE
When will it be released?

### ISSUE THREAD

**Issue by Jeff-liujianfeng** [wvangansbeke/Unsupervised-Classification#1]
Our team is very interested in your work. When will your code be made public?
Thank you!

**Comment by choosehappy** [comment]
second!

**Comment by wvangansbeke** [comment]
Hi @Jeff-liujianfeng,

We are currently making the code ready for publication. It's hard to give an exact date, but it should be available before the camera ready deadline (17 July). 

Best, 
Wouter

**Comment by AmeenAli** [comment]
Hi,
Its 22 already, anything new with the code?
Thanks alot!

**Comment by wvangansbeke** [comment]
The code is released.

**Comment by Jeff-liujianfeng** [comment]
Thanks!
