### ISSUE TITLE
results after selflabel.py on CIFAR100 not include some classes?

### ISSUE THREAD

**Issue by jimmy19991222** [wvangansbeke/Unsupervised-Classification#101]
Hi, thanks for sharing this excellent work.

I try to cluster CIFAR100 dataset to 100 classes using SCAN. I just change "num_classes" in config file and train. After running scan.py, the result is ok. However, after performing the self-labeling step i.e. selflabel.py, I find that the output only includes 45 classes. It seems that some classes wouldn't be selected after selflabel.

What should I do about that?

**Comment by wvangansbeke** [comment]
Hi @jimmy19991222,

We followed prior work for CIFAR100 and used the 20 superclasses to allow a fair comparison. Have a look at ImageNet if you're interested in the performance in more complex scenarios. We show the results for 50, 100, 200 and 1000 ImageNet classes. The code and config files are provided as well.

**Comment by jimmy19991222** [comment]
Thanks, I will try that.
