### ISSUE TITLE
how to evaluate the result of overclustering

### ISSUE THREAD

**Issue by vmmm123** [wvangansbeke/Unsupervised-Classification#102]
Hello, I am impressed by your work, and I am wonderring the way of evaluation on overclustering, since the hungarian algorithm can not be used for many-to-one mapping. Or could you please show the code?

**Comment by wvangansbeke** [comment]
Hi @vmmm123,

It's simpler than applying a hungarian matching algorithm. We use majority voting to assign all samples of a certain cluster to the same ground truth class. So, for each cluster, you need to loop over all the ground truth classes and keep track of largest overlap with a counter. It's pretty straightforward. You can also find more info in previous issues.

**Comment by Dadatata-JZ** [comment]
> Hi @vmmm123,
> 
> It's simpler than applying a hungarian matching algorithm. We use majority voting to assign all samples of a certain cluster to the same ground truth class. So, for each cluster, you need to loop over all the ground truth classes and keep track of largest overlap with a counter. It's pretty straightforward. You can also find more info in previous issues.

Hi @wvangansbeke is there any intuition behind applying hungarian matching algorithm? I can see it is simple and efficient! That drives me more crazy to know the intuition behind. Any alternatives you thought or explored during that time? tyty
