### ISSUE TITLE
how to decide the number of clusters

### ISSUE THREAD

**Issue by zhaotf16** [wvangansbeke/Unsupervised-Classification#103]
Dear author,
     Thanks for your contribution and this is really a good work. Here I have a small question about over-clustering.

     When I applied SCAN to my own dataset, I don't know how to choose a good cluster number because categories/classes of this dataset is unknown and can be dramatic. Could you give me some advice?

**Comment by wvangansbeke** [comment]
Hi @zhaotf16,

We argue that it should be doable to make a well-educated guess. You could also calculate the entropy over the cluster assignments to check if the uniformity constraint is satisfied. If not, it is likely that you should increase the amount of clusters.
