### ISSUE TITLE
Regarding the consistency_loss in SCAN loss

### ISSUE THREAD

**Issue by XiHuYan** [wvangansbeke/Unsupervised-Classification#107]
Thanks for sharing your excellent work!

For the consistency_loss in SCANLoss, it's a dot product of two soft cluster assignment vectors and takes log. My question is that, if the dot product of two vectors is negative, then the consistency loss will be invalid. But I didn't see you handle this numerical problem in your code.

**Comment by wvangansbeke** [comment]
Hi @XiHuYan,

The input of the loss are probabilities. These are positive by definition.

**Comment by XiHuYan** [comment]
Sorry, my bad
