### ISSUE TITLE
eval can't run the result

### ISSUE THREAD

**Issue by kkellyk** [wvangansbeke/Unsupervised-Classification#117]
Hi,
I run the `!python eval.py --config_exp configs/scan/scan_cifar10.yml --model repository_eccv/cifar-10/scan/model.pth.tar --visualize_prototypes` but but no result:

> Load model weights ...
> Perform evaluation of the clustering model (setup=scan).
> Figure(640x480)
> {'ACC': 0.8142, 'ARI': 0.658409853352927, 'NMI': 0.7090852722819195, 'ACC Top-5': 0.9885, 'hungarian_match': [(0, 8), (1, 7), (2, 0), (3, 6), (4, 9), (5, 3), (6, 5), (7, 2), (8, 1), (9, 4)]}
> Get topk
> Figure(640x480)
> Figure(640x480)
> Figure(640x480)
> Figure(640x480)
> Figure(640x480)
> Figure(640x480)
> Figure(640x480)
> Figure(640x480)
> Figure(640x480)
> Figure(640x480)

I added `%matplotlib inline` at the top of visualize_indices function in the eval.py file.
But the result is still the same.

How can I do?
Thanks
Kelly

**Comment by emessori** [comment]
Hello, could you please share the solution if you solved the issue?
Thank you and have a great day.
