### ISSUE TITLE
Why do you need target (label) on fill_memory_bank??

### ISSUE THREAD

**Issue by edwardcho** [wvangansbeke/Unsupervised-Classification#119]
Hello Sir,

I found that fill_memory_bank needs targets (label) on simclr(pretext).
I don't know why do you need target on unsupervised classification.

```python
On page 3 in your paper.
2.1Representation learning for semantic clustering
    .... However, when we do not have access to such ground-truth labels ....
```

Thanks,
Edward Cho.

**Comment by wvangansbeke** [comment]
We use labels in order to evaluate the algorithm (e.g., knn evaluation).
