### ISSUE TITLE
imagenet100

### ISSUE THREAD

**Issue by AmeenAli** [wvangansbeke/Unsupervised-Classification#12]
Hi
where can I find the Imagenet100 version?

**Comment by wvangansbeke** [comment]
ImageNet-100 uses 100 randomly selected classes from ImageNet. So you have to download the complete ImageNet dataset first. This does not happen automatically. You need to set your path to the correct directory as described in the README. Then the classes are loaded from `data/imagenet_subsets` if you specify ImageNet-100.
