### ISSUE TITLE
Is knn for validation?? (memory bank, target(label))

### ISSUE THREAD

**Issue by edwardcho** [wvangansbeke/Unsupervised-Classification#120]
Hello Sir,

I still have some problem.
Is knn for validation (pretext, scan, selflabeling)??

If so, memory bank and targets are do not need for training??

Thanks,
Edward Cho.

**Comment by edwardcho** [comment]
Hello Sir,

I found that knn needs for scan clustering. ('anchor' and 'neighbor')
So memory bank and target(label) do need. Right?

Thanks,
Edward Cho.

**Comment by wvangansbeke** [comment]
We only use labels during evaluation. You can't compute the knn accuracy without targets.
