### ISSUE TITLE
If an unlabeled dataset is used how should the target variable be handled?

### ISSUE THREAD

**Issue by kkellyk** [wvangansbeke/Unsupervised-Classification#121]
Hi author,
According to my observations, there are target variables in `Memory_Bank()`, `fill_memory_bank()`,` contrastive_evaluate()`, `get_predictions()`, `NeighborsDataset()`, `hungarian_evaluate()`, `hungarian_match()` and `MaskedcrossEntropyLoss()`.
Since I am using unlabeled data so I do not have a label. 
How should I implement this project?

Thanks.

**Comment by wvangansbeke** [comment]
Hi,

If you don't have labels available, you can't perform the evaluation part.

**Comment by kkellyk** [comment]
Thank you~~
