### ISSUE TITLE
Normalization on custom dataset

### ISSUE THREAD

**Issue by emessori** [wvangansbeke/Unsupervised-Classification#129]
Hello! Thank you for your useful work.
I want to apply your model to a new dataset of images: I already made all the config files necessary by 'copying' the ones for ImageNet and modifying them accordingly. However, I am confused about the criteria used here for normalization, since an array for the mean and the standard deviation is provided. How do you retrieved these values? Are they computed w.r.t. the single channel?
E.g. from configs/pretext/moco_imagenet50.yml
`# Transformations
transformation_kwargs:
   crop_size: 224 # maybe this crop size is too small; we'll see.
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
`
I suppose that the first entry in the mean array 0.485, for example, is computed by taking into account the red channel of each image in the dataset. I want to make sure I am understanding this right so that I can use your code in the best way possible :)

Thank you and have a great day.

**Comment by wvangansbeke** [comment]
Yes, format is RGB.
