### ISSUE TITLE
train on whole imagenet

### ISSUE THREAD

**Issue by AmeenAli** [wvangansbeke/Unsupervised-Classification#16]
Hello
I would like to run an expermint and train on the whole imagenet dataset and not only (50 , 100 , 200 classes)
any idea how can i train a moco model from scratch? and how many epoches its supposed to be done?
thanks for sharing the code!

**Comment by AmeenAli** [comment]
Specially I have created a new config file for the whole imagenet dataset (1000 classes) and I always get cuda out of memory even with batchsize = 4!

**Comment by wvangansbeke** [comment]
Hi again, 

If you want to run MoCo from scratch, I refer to the [MoCo repo](https://github.com/facebookresearch/moco). We use their pretrained model for ResNet50 on ImageNet which was trained for 800 epochs (this pretrained model is downloaded automatically in `moco.py`). It will take a while to train this model from scratch though. 

Are you running `moco.py`? Then it's probably running out of memory when computing the nearest neighbors on the gpu, which has nothing to do with the batch size. For the nearest neighbors search, it stores all features on the gpu which takes at least 13gb. You can also perform this operation on the cpu by commenting out [this line](https://github.com/wvangansbeke/Unsupervised-Classification/blob/master/utils/memory.py#L52) but it will take much longer of course (I never tried this). 

Hope this helps.

**Comment by AmeenAli** [comment]
@wvangansbeke Thanks for your fast response,
so if I understand correctly its enough to run python moco.py with the new config file for ImageNet1000 while using the pretrained model?

**Comment by wvangansbeke** [comment]
Hi @AmeenAli,

The `train_db_name` in the config file should be `imagenet` to load the correct dataset (check [this line](https://github.com/wvangansbeke/Unsupervised-Classification/blob/master/utils/common_config.py#L135)). You can also change `num_classes` to 1000. You don't need to change anything else actually.
