### ISSUE TITLE
KeyError: 'temperature'

### ISSUE THREAD

**Issue by cxr12345** [wvangansbeke/Unsupervised-Classification#18]
Dear Author:
I tried to run 
           `python3 scan.py --config_env configs/cifer_env.yml --config_exp configs/scan/scan_cifar10.yml`
but this error occurred 
```
File "moco.py", line 57, in main
    memory_bank_train = MemoryBank(len(train_dataset), 2048, p['num_classes'], p['temperature'])
KeyError:'temperature'
```
Later, I looked for the element of the p dictionary, but did not find the element temperature. The p dictionary is as follows: `{'setup':'scan','criterion':'scan','criterion_kwargs': {'entropy_weight': 5.0} ,'update_cluster_head_only': False,'num_heads': 1,'backbone':'resnet18','train_db_name':'cifar-10','val_db_name':'cifar-10','num_classes': 10,'num_neighbors' : 20,'augmentation_strategy':'ours','augmentation_kwargs': {'crop_size': 32,'normalize': {'mean': [0.4914, 0.4822, 0.4465],'std': [0.2023, 0.1994, 0.201] },'num_strong_augs': 4,'cutout_kwargs': {'n_holes': 1,'length': 16,'random': True}},'transformation_kwargs': {'crop_size': 32,'normalize': {' mean': [0.4914, 0.4822, 0.4465],'std': [0.2023, 0.1994, 0.201]}},'optimizer':'adam','optimizer_kwargs': {'lr': 0.0001,'weight_decay': 0.0001} ,'epochs': 50,'batch_size': 128,'num_workers': 8,'scheduler':'constant','pretext_dir':'./output/cifar-10/pretext','pretext_checkpoint':'./ output/cifar-10/pretext/checkpoint.pth.tar','pretext_model':'./output/cifar-10/pretext/model.pth.tar','topk_ne ighbors_train_path':'./output/cifar-10/pretext/topk-train-neighbors.npy','topk_neighbors_val_path':'./output/cifar-10/pretext/topk-val-neighbors.npy','scan_dir' :'./output/cifar-10/scan','scan_checkpoint':'./output/cifar-10/scan/checkpoint.pth.tar','scan_model':'./output/cifar-10/scan/ model.pth.tar','selflabel_dir':'./output/cifar-10/selflabel','selflabel_checkpoint':'./output/cifar-10/selflabel/checkpoint.pth.tar','selflabel_model': ' ./output/cifar-10/selflabel/model.pth.tar'}`
Do you know what's going on, thank you

**Comment by wvangansbeke** [comment]
Hi @cxr12345,

I think you're running the wrong file since the error appears in `moco.py` while you're running `scan.py`. For `scan.py` no temperature is needed.

**Comment by cxr12345** [comment]
> 嗨@ cxr12345，
> 
> 我认为您正在运行错误的文件，因为`moco.py`在运行时会出现错误`scan.py`。因为`scan.py`不需要温度。

I'm so sorry, it may be that I run the wrong file, I reorganized it again, the following are three small problems I encountered:
1⃣️When I run simclr.py (`python3 simclr.py --config_env configs/env.yml --config_exp configs/scan/scan_cifar10.yml`), it will appear:
```
File "simclr.py", line 66, in main
     p['model_kwargs']['features_dim'],
KeyError:'model_kwargs'
```
2⃣️When I run moco.py (`python3 moco.py --config_env configs/env.yml --config_exp configs/scan/scan_cifar10.yml`), it will appear
```
File "moco.py", line 57, in main
     memory_bank_train = MemoryBank(len(train_dataset), 2048, p['num_classes'], p['temperature'])
KeyError:'temperature'
```
3⃣️I want to ask if I look at the dataset for training myself, which file should I run?
Thank you very much

**Comment by wvangansbeke** [comment]
Ok I see. You're running the wrong config file. Have a look at the README. You should be running the config file for simclr or moco in your case. Have a look at the folder `configs/pretext`.

**Comment by cxr12345** [comment]
Great, thank you very much, let me try
