### ISSUE TITLE
Experiment about SOTA Comparison

### ISSUE THREAD

**Issue by limai1990** [wvangansbeke/Unsupervised-Classification#2]
You have done great work! I have a question about the experiments.
As you have mentioned in your paper, _Unsupervised Feature Learning via Non-Parametric Instance Discrimination_ is used as a representing learning method, but this paper seems to present the result of unsupervised classification in CIFAR-10. Why didn't you include it when comparing with SOTA? Is it because the task it does is not exactly equivalent to yours?

**Comment by SimonVandenhende** [comment]
Indeed, we use the referred representation learning method. However, notice that representation learning methods still required supervised finetuning or an off-line clustering technique (e.g. K-means) to obtain the class assignments from the model. In the ablation studies we already showed that the latter is suboptimal, and outperformed by our work. We recently uploaded an updated version of the paper to arxiv, where we include the pretext+kmeans experiment in the sota comparison (when using the SimCLR implementation of the instance discrimination pretext task).

**Comment by limai1990** [comment]
Thanks for your quick reply.
As shown in Table 1 of its paper, combing representation learning and Nearest Neighbor can achieve 80.4% top-1 classiﬁcation accuracy in CIFAR-10 dataset without using self-labeling. Is this experiment different from your unsupervised classification experiment?

**Comment by SimonVandenhende** [comment]
In order to assign each sample to one of ten clusters using kNN, one needs ground-truth annotations. This is not the case for our model, which immediately predicts the cluster assignment.

**Comment by limai1990** [comment]
Thank you for your time, you really helped. I didn't know enough about KNN before.
