### ISSUE TITLE
About number of clusters in SCAN

### ISSUE THREAD

**Issue by suzhenghang** [wvangansbeke/Unsupervised-Classification#28]
Hello，if I want to deal with big dataset like OpenImages (about 5000+ classes)，should I set the cluster num 5000

**Comment by wvangansbeke** [comment]
Hi @suzhenghang,

I'm not sure what you exactly want to achieve on OpenImages. Indeed, you can always try to overcluster, but I doubt it will work that easily. You can always try 10k clusters but I would advise to check the nearest neighbours first after training the pretext task. Keep in mind that ImageNet is object centered and only has one instance in the image which makes it much easier than OpenImages. OpenImages is quite ambiguous if you ask me. 

Hope this helps.

**Comment by wvangansbeke** [comment]
Feel free to ask more questions if something is unclear. I'm closing this for now though.
