### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by daniiki** [wvangansbeke/Unsupervised-Classification#36]
Hi again, 

when running simclr.py I receive the following error: 
RuntimeError: Given input size: (512x3x3). Calculated output size: (512-3x-3). Output size ist too small. 

What does this mean? Has this something to so with the size of my images? Or with the size value I specify in my .yml file  for Transformation? 
How can I solvr this error? 
Thank you so much for your fast answers and your patience!!

**Comment by wvangansbeke** [comment]
Hi @daniiki,

Yes there is something wrong with your input size. For ImageNet we use an input size of 224x224x3. So make sure it has the same format. Yes the size value in the yml file will be used for center-cropping. Maybe try with ImageNet dataset first, which you can use as an example.

**Comment by daniiki** [comment]
My images are in the size of 1600x1200 px. Is it really necessary to change the size of them? I changed the kernel size value in resnet-stl.py of average pooling from 7 to 3. Now it seems to work. Is this alright or does this destroy something?

**Comment by wvangansbeke** [comment]
Hi @daniiki,

I think training will take a lot of time with that resolution though. Yes, you might indeed need to change the network architecture slightly. Maybe consider resizing the images to at least to 512 x 512. 

Since you don't have any ground truth available, you will have to check the results qualitatively. Just random sample a few images and check their nearest neighbours.

**Comment by daniiki** [comment]
Alright. Thank you so much!!

**Comment by daniiki** [comment]
Hi @wvangansbeke, 

I have again a couple of questions: 
- what exactly is the MemoryBank good for? What is stored in the MemoryBank? 
- I still cant figure out how to check the quality of the nearest neighbours. I can call the saved model after running simclr and get outputs: output=model (images), but that are not the nearest neighbours? 

I found out that there ist a .npy file stored with the top k nearest neighbours during Training? Do I have to load this file?  

I'm sorry for the silly questions, but I'm a newbie in deep learning and coding.
