### ISSUE TITLE
Tutorial for custom datasets:

### ISSUE THREAD

**Issue by arbab97** [wvangansbeke/Unsupervised-Classification#37]
It will be of great help if a tutorial to run the custom datasets is written. 
Right now there's a lot of complexity due to dataset/data loader classes. It will make it easier for people from different domains to experiment with SCAN.

**Comment by wvangansbeke** [comment]
Hi @arbab97,

Yes I see. I might write a second tutorial for a custom dataset when I have time.

**Comment by arbab97** [comment]
Will be great. 
Looking forward ..
