### ISSUE TITLE
have you encountered the performance degeneration in self-label steps?

### ISSUE THREAD

**Issue by ZhiyuanDang** [wvangansbeke/Unsupervised-Classification#42]
Hi, thanks for your great works. I have trained a model with a new loss by using scan.py. The performance is good before fed into self-label steps. Have you encountered this problem? How to address it?

**Comment by wvangansbeke** [comment]
Hi @ZhiyuanDang,

I answered a similar question in issue #21. I really think that one is helpful.

In short, it depends on the dataset:
Self-labeling provides noticable improvements for cifar10, cifar20, imagenet50, imagenet100 and imagenet200. If some clusters are missing, (i.e. there are not enough confident samples or the clusters do not align well with the ground truth after the SCAN-step) the self-labeling step is likely going to reduce the accuracy. You can prevent this by using a few tricks, i.e. EMA or multiple clustering heads.

**Comment by ZhiyuanDang** [comment]
ok, thanks for your reply
