### ISSUE TITLE
overclustering

### ISSUE THREAD

**Issue by txw1997** [wvangansbeke/Unsupervised-Classification#43]
Hello, I want to know how could I overcluster a dataset, just change the num_classes in yml file? 
Such as, cluster a cifar10 to 20 classes?  Thanks

**Comment by wvangansbeke** [comment]
Hi @txw1997,

Thank you for your interest.

I believe issue #29 will be helpful. Yes you can simply increase the amount of clusters, but be aware that the evaluation is currently only provided for a one-to-one mapping. You will have to solve a binary integer problem to get the exact mapping here, (many-to-one).

Hope this helps.

**Comment by txw1997** [comment]
understand, thank you~
