### ISSUE TITLE
How to test the SCAN trained model on a full image? 

### ISSUE THREAD

**Issue by happyCodingSusan** [wvangansbeke/Unsupervised-Classification#47]
Hi @wvangansbeke, Thank you for sharing you work! Your results look amazing!

To train SCAN, each input image must be a tightly cropped image containing a single object. So if there are multiple classes on an image, in order to test a SCAN trained model on the image, it needs to run a 2D object detector to detect all objects first, crop them and then test the SCAN model on each cropped image. Right?

**Comment by wvangansbeke** [comment]
Hi @happyCodingSusan,

Thank you for trying out our code. 

Ideally yes. Self-supervised learning when there are multiple instances in a single image, is still an open problem.

**Comment by wvangansbeke** [comment]
Hi @happyCodingSusan,

If something is still unclear, let us know. I'm closing this for now.
