### ISSUE TITLE
embedding space

### ISSUE THREAD

**Issue by smallelephant9516** [wvangansbeke/Unsupervised-Classification#53]
It looks like an amazing work. However, I feel like I need some help. I have an unlabeled dataset and I want to get a general understanding of my dataset by looking at the higher level of representation on each image in the embedding space. Where I could check the embedding of each image to visualize the cluster? Thanks for your help.

**Comment by wvangansbeke** [comment]
Hi @smallelephant9516,

Thank for your interest and trying out the code. 

You could "overcluster" your dataset and visualize the prototype of each cluster to get an idea what each cluster represents. 
I would also take a look at the nearest neighbors.

Have a look at `eval.py` to visualize the prototypes. I believe this will be helpful.

**Comment by wvangansbeke** [comment]
Hi @smallelephant9516,

If you have any more issues, let us know. Closing this for now.
