### ISSUE TITLE
Data Imbalance is a problem. 

### ISSUE THREAD

**Issue by rajat-tech-002** [wvangansbeke/Unsupervised-Classification#55]
Hy. I have tried the code for datasets after introducing class imbalance. The model is not able to perform well for such datasets. Also, if the number of classes are high, more than 50, the model is not able to outperform kmeans. 
Why so.? Even if we try to balance classes in self label step. 
Is it the weakness of entropy term in SCAN loss? 
You work is really good. But for real world datasets like high number of classes and skewed dataset,  how to modify it? Thanks

**Comment by wvangansbeke** [comment]
Hi @rajat-tech-002,

Thank you for your interest in our work.

Training on imbalanced (or even long-tailed data distributions) is a general problem in both supervised and self-supervised learning. To improve the performance in this scenario, you can relax the uniformity constraint (i.e. use a lower weight lambda) or perform _overclustering_ such that the clusters are uniform.  I have never experimented with 50+ classes on imbalanced datasets, but I'm convinced that this should help.
For ImageNet, we were able to outperform K-Means (see paper). However, you can see that the improvements diminish when we increase the amount of classes. When you have a lot of classes (i.e. 1000+) and long-tailed data distributions, K-Means should perform quite well compared to learnable clustering methods. This still requires further research.

**Comment by wvangansbeke** [comment]
If you have further questions, let me know.
