### ISSUE TITLE
would you please provide the results  on all cifar10(60000examples)?

### ISSUE THREAD

**Issue by miziha-zp** [wvangansbeke/Unsupervised-Classification#56]
most methods in early year used all of the samples to train a cluster method without label. to my best knowledge, scan are the first method train for 50000 and test for 10000 in this clustering question.  So did you try your work on all examples?

**Comment by wvangansbeke** [comment]
Hi @miziha-zp,

Yes. You should see some improvement on all datasets. This can make a large difference on STL-10 for example. On CIFAR-10 is shouldn't be more than 1-2%.

**Comment by miziha-zp** [comment]
thanks for your sharing ,when I modify your code in `data/cifar.py` row 66-69
```python
if self.train:
     downloaded_list = self.train_list 
else:
    downloaded_list = self.test_list 
``` 
to
```python
if self.train:
    downloaded_list = self.train_list + self.test_list
else:
    downloaded_list = self.test_list + self.train_list
```

and rerun below

```bash
nohup python simclr.py --config_env configs/env.yml --config_exp configs/pretext/simclr_cifar10.yml > logs/triansimclr.log 2>&1 &
nohup python scan.py --config_env configs/env.yml --config_exp configs/scan/scan_cifar10.yml > logs/trianscan.log 2>&1 &
nohup python selflabel.py --config_env configs/env.yml --config_exp configs/selflabel/selflabel_cifar10.yml > logs/selflabel.log 2>&1 &
```

result:
last:
'ACC': 0.8375, 'ARI': 0.730, 'NMI': 0.7851, it seems like get worse result, did I miss some things?

**Comment by wvangansbeke** [comment]
Hi @miziha-zp,

You should be able to get improvement. You can compare your intermediate results (nearest neighbors and ACC) with ours (see readme) and check where it goes wrong. If this still doesn't help, just perform the first step on all the data.  Results should be slightly better on CIFAR10.
