### ISSUE TITLE
Question regarding Fig2 in paper

### ISSUE THREAD

**Issue by zhangdan8962** [wvangansbeke/Unsupervised-Classification#57]
Hi,

I am wondering how you got the result for ImageNet in Fig.2? Specifically, how many samples and what kind of representations did you use to get such statistics?

Also, I realized that as MOCO being pretext, you used 2048-d representation to calculate KNN. I am wondering why you did not use 128-d vector instead because you did use 128-d vector in context of SimCLR being pretext.

**Comment by wvangansbeke** [comment]
Hi @zhangdan8962,

I appreciate your interest in our work.

We simply checked how many neighbors have the same label as its anchor after solving the pretext task (i.e. instance discrimination). You can either use the feature space before the MLP or after the MLP to monitor the KNN. They will be highly correlated anyway. It is slightly bettter to take the 2048d vectors, but differences are small on full ImageNet.

**Comment by zhangdan8962** [comment]
Did you test on full ImageNet?

**Comment by wvangansbeke** [comment]
Hi @zhangdan8962,

Yes we did. We provide numbers for 50, 100, 200 and 1000 classes in the paper. Fig. 2 also shows the nearest neighbors accuracy on full ImageNet, i.e. 1000 classes.
