### ISSUE TITLE
Question on SimCLR loss

### ISSUE THREAD

**Issue by rajat-tech-002** [wvangansbeke/Unsupervised-Classification#59]
Hy
@wvangansbeke , can you please tell whether the loss value returned by SimCLR function is averaged over the batch or not? This Instance-CL loss is SimCLR loss only.
![image](https://user-images.githubusercontent.com/46721220/117616482-d0b31d00-b188-11eb-9d6b-cb4be86c7d42.png)

![image](https://user-images.githubusercontent.com/46721220/117616417-bd07b680-b188-11eb-8e7e-29b2c3c2c18e.png)

**Comment by wvangansbeke** [comment]
Hi @rajat-tech-002,

Yes, we take the mean over the batch. Check the last line of the SimCRL-loss ([here](https://github.com/wvangansbeke/Unsupervised-Classification/blob/master/losses/losses.py#L163)).
