### ISSUE TITLE
About NeighborsDataset's neighbor and possible_neighbors

### ISSUE THREAD

**Issue by woolpeeker** [wvangansbeke/Unsupervised-Classification#62]
Excellent work, thanks for the public codes.

I found the paper says that during computing scan loss, neighbor samples of an anchor sample are used.
But from the code, only the nearest sample is used which is the "neighbor" in outputs of NeighborsDataset
The other neighbors which are "possible_neighbors" in outputs of NeighborsDataset are not used.
Is there any reason or impacts?

**Comment by wvangansbeke** [comment]
Hi @woolpeeker,

We randomly sample from the set of nearest neighbors. See also issue #4 for a more detailed answer.
If you have any more questions, let me know.

**Comment by woolpeeker** [comment]
My bad.

Thanks for quick reply.
