### ISSUE TITLE
parallelization in simclr model

### ISSUE THREAD

**Issue by hyungkwonko** [wvangansbeke/Unsupervised-Classification#67]
Hi,

I found that current model does not use DataParallel in simclr.py:

https://github.com/wvangansbeke/Unsupervised-Classification/blob/0eb8ab344068e5fcf1e5cb5ef58f4b623b2b6e54/simclr.py#L38

I guess this can be easily parallelized as did in:

https://github.com/wvangansbeke/Unsupervised-Classification/blob/0eb8ab344068e5fcf1e5cb5ef58f4b623b2b6e54/scan.py#L48

I was thinking whether there Is any special reason for not using the parallelization.

By the way, thank you very much for the great work.

Kwon

**Comment by wvangansbeke** [comment]
Hi @hyungkwonko,

Thank you for your interest.

Yes indeed, `nn.DataParallel` will work as well in `simclr.py`. 
No important reason why we didn't use it here. Saving and loading just needs to be consistent. Either save `model.state_dict()` or `model.module.state_dict()`. We used the latter.

**Comment by hyungkwonko** [comment]
Thank you for the reply.
Will close this issue.
