### ISSUE TITLE
Overclustering

### ISSUE THREAD

**Issue by abrar360** [wvangansbeke/Unsupervised-Classification#70]
I'm having trouble understanding how exactly metrics are using hungarian matching computed for overclustering when the number of predicted clusters doesn't match the ground truth. The paper says there's some kind of many-to-one mapping but I'm not sure how this works. I'd appreciate a more detailed explanation.

**Comment by wvangansbeke** [comment]
Hi @abrar360,

Good question. I refer you to a few older issues: #63 #43 #29. 
In short, we look for the majority class for each cluster and assign all elements to that particular class.
