### ISSUE TITLE
Getting error while running scan.py

### ISSUE THREAD

**Issue by gauravjain10** [wvangansbeke/Unsupervised-Classification#72]
Epoch 1/100
---------------
Adjusted learning rate to 5.00000
Train ...
Epoch: [0][0/2]	Total Loss -1.4936e+00 (-1.4936e+00)	Consistency Loss 3.0481e-01 (3.0481e-01)	Entropy 3.5969e-01 (3.5969e-01)
Make prediction on validation set ...
Evaluate based on SCAN loss ...
**similarity shape torch.Size([96, 96])
neighbors shape torch.Size([2016])
anchors shape torch.Size([2016])**
Traceback (most recent call last):
  File "scan.py", line 142, in <module>
    main()
  File "scan.py", line 104, in main
    scan_stats = scan_evaluate(predictions)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/content/drive/My Drive/LDA_image/baselines/SCAN/custom_scan/utils/evaluate_utils.py", line 109, in scan_evaluate
    similarity = similarity[anchors, neighbors]
IndexError: index 97 is out of bounds for dimension 1 with size 96
########################################################################
I am trying to check on custom dataset which contains only two classes.
I am not sure how similarity shape is [96,96].can you please tell me how can i resolve this error
thanks and regards

**Comment by gauravjain10** [comment]
okay it got resolved by reducing batch size.
anyway after training part is complete through scan.py
I am getting only 0.5 accuracy.It is actually predicting values to class 1.So which hyper parameter i can tune considering i have only two classes

**Comment by wvangansbeke** [comment]
Hi @gauravjain10,

Thank you for your interest.
Hard to say (depends on the type of data, imbalance, etc.) Are the images in each class visually similar? What are the classes? Are you sure that the pretext task is trained properly? Maybe use KMeans to verify that first. To answer your question, you can always reduce the weight for the uniformity loss if you think that's an issue.

**Comment by gauravjain10** [comment]
Hi @wvangansbeke thank you for quick response.

Yeah so I am working solar radio burst images .Although I have given balanced dataset.And yeah both classes are some what similar only difference in one class there is solar burst other does not have it.As you said i will check the pretext task and i will also look for weight for uniformity loss(can you tell which hyper-param you have defined for weight control

**Comment by wvangansbeke** [comment]
Hi @gauravjain10,

Ok.  Hard to say since I'm not familiar with the data but let me know if you have still issues. I'm closing this for now. Checking the intermediate results (e.g. pretext task results and nearest neighbors) is definetely a good place to start. Good luck.
