### ISSUE TITLE
Why not parallelize the implementation of simclr.py 

### ISSUE THREAD

**Issue by batradhruv** [wvangansbeke/Unsupervised-Classification#76]
I was looking at your code and noticed that you didnt include "model = torch.nn.DataParallel(model)" wrapper to parallelize across GPUs. This is for simclr.py. 

If I look at your implementation for scan.py, I do see this section. Could you provide some information on why not?

**Comment by wvangansbeke** [comment]
Hi @batradhruv,

Thank you for your interest.
Sure. You can do this. Wanted to keep it clean. Issue #67 might be helpful.

**Comment by batradhruv** [comment]
Would you like me to submit a Pull request for this? I tried the solution suggested in #67 and seems to work for me. 
My code is here - https://github.com/batradhruv/Unsupervised-Classification/commit/f5b7db301b7801af585f95f85c96e7ee067f4eec

Since training simclr takes a while, it could help other people trying out SCAN.

**Comment by wvangansbeke** [comment]
Hi @batradhruv,

Ok. Good that it works now! 
I see your point. I believe this is pretty standard. I just want to make sure that our provided models can still be loaded without any problems. I think it should be fine though since the single gpu model is loaded.
