### ISSUE TITLE
Using a custom dataset

### ISSUE THREAD

**Issue by ggndtes** [wvangansbeke/Unsupervised-Classification#8]
Hi @wvangansbeke, thank you for publishing your work.

I am totally new to the world of computer vision and came across your work by browsing the 'self-supervised-learning' GitHub tag.

I would like to cluster a custom dataset I collected online for a personal project and was wondering if it is currently possible to adapt your code to run against it. Any guidance would be appreciated, I will study the code in more details in the coming days.

Many thanks.

Harry

**Comment by wvangansbeke** [comment]
Hi Harry,

First, you have to point to the location of your dataset in `utils/mypath.py`. Then make a class for your dataset similar to the ones in the `data` folder. For example, have a look at the `__getitem__` method [here](https://github.com/wvangansbeke/Unsupervised-Classification/blob/master/data/cifar.py#L105). I suppose you can do something very similar for your custom dataset.  If the dataloading is correct, you can start running the pretext task and the clustering step as described in the README.

Hope this helps.

**Comment by ggndtes** [comment]
Many thanks for your prompt reply, Wouter - this is much appreciated. I will follow your suggestions.

Many thanks again.

H.

**Comment by wvangansbeke** [comment]
I will close this for now.
