### ISSUE TITLE
CIFAR20 evaluation issue

### ISSUE THREAD

**Issue by Xinyu-ustc** [wvangansbeke/Unsupervised-Classification#80]
Hi, thanks for your excellent work!

I try to first evaluate the performance on CIFAR100-20 using the selflabel model link you provide. And I just got 'ACC': 47.23 instead of the reported 50.7. Could you provide the variance on the final selflabel accuracy for CIFAR100-20? Thanks!

**Comment by wvangansbeke** [comment]
Hi @Xinyu-ustc,

Thanks for pointing this out.
It could be that I didn't share the best model (50.7%) but one closer to the average. I find this weird but I'm not sure anymore, would have to check it myself. The average and standard deviation are 45.9% and 2.7% respectively after the self-labeling step (see Table 3 in the paper), when running it 10 times.  So your results seem fine.

**Comment by Xinyu-ustc** [comment]
Thanks!
