### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Project/Unsupervised-Classification-master/result/cifar-10\\pretext\\topk-train-neighbors.npy'

### ISSUE THREAD

**Issue by starsky68** [wvangansbeke/Unsupervised-Classification#85]
请问，在运行scan.py的时候遇到这个问题：
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Project/Unsupervised-Classification-master/result/cifar-10\\pretext\\topk-train-neighbors.npy'

如何解决？

**Comment by wvangansbeke** [comment]
Hi @starsky68,

The file get's created at the end of the pretext task training. So either your paths are not set properly or you didn't create the file.
