### ISSUE TITLE
Download Links for CIFAR broken?

### ISSUE THREAD

**Issue by ctataryn** [wvangansbeke/Unsupervised-Classification#87]
I've tried downloading both the [CIFAR10](https://drive.google.com/file/d/1Cl5oAcJKoNE5FSTZsBSAKLcyA5jXGgTT/view?usp=sharing) and [CIFAR100](https://drive.google.com/file/d/1huW-ChBVvKcx7t8HyDaWTQB5Li1Fht9x/view?usp=sharing) dataset as laid out in the README, however both files download to a size of 44,972 KB and I cannot open them with tar. It complains:

```
tar xvf ~/Downloads/simclr_cifar-10.pth.tar
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

Can someone confirm that the links are still valid?

**Comment by wvangansbeke** [comment]
Hi @ctataryn,

You don't need to untar. The models are saved and loaded in `.pth.tar` format.

**Comment by ctataryn** [comment]
I see, thank you. I'm pretty new to ML, and I was wondering… if I have my own dataset of images that I would like to have classified, how could I go about doing so? Any guidance you could provide would be greatly appreciated.

**Comment by ctataryn** [comment]
@wvangansbeke disregard my previous query about custom dataset. I found the other issues where people asked the same question and I'm perusing the answers there.
