### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './results/cifar-10\\pretext\\model.pth.tar'

### ISSUE THREAD

**Issue by Cappuccino-Sugar** [wvangansbeke/Unsupervised-Classification#88]
Hello, I have some problems running this code, as follows：
ERROR：FileNotFoundError: [Errno 2] No such file or directory: './results/cifar-10\\pretext\\model.pth.tar'
Could you help me？
Think you

**Comment by wvangansbeke** [comment]
Hi @Cappuccino-Sugar,

Did you download the pretext file and put in the correct directory? Please follow the readme.md or tutorial.md. That should be helpful.

**Comment by Cappuccino-Sugar** [comment]
Thank you very much for your reply.
If I don't import the pretext file，e.g. simclr_stl-10.pth.tar, the above error will appear.
How to train the network if you don't import it

**Comment by wvangansbeke** [comment]
Yes. You should either download the file and place in the correct directory or run the pretext task for yourself. Please follow the readme.
