### ISSUE TITLE
Overclustering with Majority Voting Details

### ISSUE THREAD

**Issue by abrar360** [wvangansbeke/Unsupervised-Classification#92]
Hi thanks for sharing the code!

There's a few details regarding overclustering I'm having a hard time understanding. You said that you can do majority voting when the number of clusters don't match ground truth. 
So in detail, the evaluation protocol is to:
1. Assign each cluster to the class which most of its examples belong to.
2. Then do we just calculate F1 score or accuracy without regard to clusters anymore using the targets assigned in step 1?
3. What is the binary assignment problem that you mentioned and how is it more accurate than majority voting?

Thanks again!

**Comment by wvangansbeke** [comment]
Hi, 

1. & 2.: correct
3. Well a binary assignment problem might work better if your predictions are quite bad (you can also enforce uniformity over the assignments for example). In our case, a majority voting works good enough.
