### ISSUE TITLE
Motivation of semantic clustering through scan-loss

### ISSUE THREAD

**Issue by wetliu** [wvangansbeke/Unsupervised-Classification#96]
Thank you for your great work. According to your paper, the performance of nearest neighbors in after pretext task can be good, but there may not be cluster structure (please correct me if I am wrong). 

May I confirm that the purpose of scan-loss is to, hopefully, pull samples together that potentially share the same labels so that cluster structure is formed? 

And is Hungarian matching algorithm actually measuring the cluster structure performance? Is it the reason why the accuracy of the pretext different from the accuracy of hungarian matching algorithm even we use the same embeddings (after pretext task is finished and before semantic clustering begins)?

Thank you so much!

**Comment by wvangansbeke** [comment]
Hi,

Evaluating the predictions does not make sense without the hungarian matching. You need to know the mapping from clusters to the ground truth classes.  

The scan-loss enforces neighboring samples to belong to the same cluster while also enforcing uniformity over the clusters. 
I refer you to the paper for more details.

**Comment by wetliu** [comment]
Thank you so much for your responds. The relationship between KNN and clusters are much clearer now. Thank you!
